services:
  - type: web
    name: love-passbook
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: FEISHU_APP_ID
        value: cli_aa9c0fff49f99cd2
      - key: FEISHU_APP_SECRET
        sync: false
      - key: BITABLE_APP_TOKEN
        value: PfZrbU7fLapzM6sRTFbci0Ownoe
      - key: TABLE_VOLUNTEERS
        value: tblgZaaGcmvrug22
      - key: TABLE_ACTIVITIES
        value: tblgcfpniTUGpCay
      - key: TABLE_STAMP_RECORDS
        value: tbl4ItI4eUN7CGAQ
